// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_messages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_messages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_messages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_messages_2eproto;
namespace nz {
namespace co {
namespace colensobbdo {
namespace dlib {
namespace proto {
class Face;
struct FaceDefaultTypeInternal;
extern FaceDefaultTypeInternal _Face_default_instance_;
class FaceList;
struct FaceListDefaultTypeInternal;
extern FaceListDefaultTypeInternal _FaceList_default_instance_;
class Landmark;
struct LandmarkDefaultTypeInternal;
extern LandmarkDefaultTypeInternal _Landmark_default_instance_;
class LandmarkList;
struct LandmarkListDefaultTypeInternal;
extern LandmarkListDefaultTypeInternal _LandmarkList_default_instance_;
class RectF;
struct RectFDefaultTypeInternal;
extern RectFDefaultTypeInternal _RectF_default_instance_;
class RectFList;
struct RectFListDefaultTypeInternal;
extern RectFListDefaultTypeInternal _RectFList_default_instance_;
}  // namespace proto
}  // namespace dlib
}  // namespace colensobbdo
}  // namespace co
}  // namespace nz
PROTOBUF_NAMESPACE_OPEN
template<> ::nz::co::colensobbdo::dlib::proto::Face* Arena::CreateMaybeMessage<::nz::co::colensobbdo::dlib::proto::Face>(Arena*);
template<> ::nz::co::colensobbdo::dlib::proto::FaceList* Arena::CreateMaybeMessage<::nz::co::colensobbdo::dlib::proto::FaceList>(Arena*);
template<> ::nz::co::colensobbdo::dlib::proto::Landmark* Arena::CreateMaybeMessage<::nz::co::colensobbdo::dlib::proto::Landmark>(Arena*);
template<> ::nz::co::colensobbdo::dlib::proto::LandmarkList* Arena::CreateMaybeMessage<::nz::co::colensobbdo::dlib::proto::LandmarkList>(Arena*);
template<> ::nz::co::colensobbdo::dlib::proto::RectF* Arena::CreateMaybeMessage<::nz::co::colensobbdo::dlib::proto::RectF>(Arena*);
template<> ::nz::co::colensobbdo::dlib::proto::RectFList* Arena::CreateMaybeMessage<::nz::co::colensobbdo::dlib::proto::RectFList>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace nz {
namespace co {
namespace colensobbdo {
namespace dlib {
namespace proto {

// ===================================================================

class Landmark final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nz.co.colensobbdo.dlib.proto.Landmark) */ {
 public:
  inline Landmark() : Landmark(nullptr) {}
  ~Landmark() override;
  explicit constexpr Landmark(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Landmark(const Landmark& from);
  Landmark(Landmark&& from) noexcept
    : Landmark() {
    *this = ::std::move(from);
  }

  inline Landmark& operator=(const Landmark& from) {
    CopyFrom(from);
    return *this;
  }
  inline Landmark& operator=(Landmark&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Landmark& default_instance() {
    return *internal_default_instance();
  }
  static inline const Landmark* internal_default_instance() {
    return reinterpret_cast<const Landmark*>(
               &_Landmark_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Landmark& a, Landmark& b) {
    a.Swap(&b);
  }
  inline void Swap(Landmark* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Landmark* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Landmark* New() const final {
    return new Landmark();
  }

  Landmark* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Landmark>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Landmark& from);
  void MergeFrom(const Landmark& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Landmark* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nz.co.colensobbdo.dlib.proto.Landmark";
  }
  protected:
  explicit Landmark(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:nz.co.colensobbdo.dlib.proto.Landmark)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class LandmarkList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nz.co.colensobbdo.dlib.proto.LandmarkList) */ {
 public:
  inline LandmarkList() : LandmarkList(nullptr) {}
  ~LandmarkList() override;
  explicit constexpr LandmarkList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LandmarkList(const LandmarkList& from);
  LandmarkList(LandmarkList&& from) noexcept
    : LandmarkList() {
    *this = ::std::move(from);
  }

  inline LandmarkList& operator=(const LandmarkList& from) {
    CopyFrom(from);
    return *this;
  }
  inline LandmarkList& operator=(LandmarkList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LandmarkList& default_instance() {
    return *internal_default_instance();
  }
  static inline const LandmarkList* internal_default_instance() {
    return reinterpret_cast<const LandmarkList*>(
               &_LandmarkList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LandmarkList& a, LandmarkList& b) {
    a.Swap(&b);
  }
  inline void Swap(LandmarkList* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LandmarkList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LandmarkList* New() const final {
    return new LandmarkList();
  }

  LandmarkList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LandmarkList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LandmarkList& from);
  void MergeFrom(const LandmarkList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LandmarkList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nz.co.colensobbdo.dlib.proto.LandmarkList";
  }
  protected:
  explicit LandmarkList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLandmarksFieldNumber = 1,
  };
  // repeated .nz.co.colensobbdo.dlib.proto.Landmark landmarks = 1;
  int landmarks_size() const;
  private:
  int _internal_landmarks_size() const;
  public:
  void clear_landmarks();
  ::nz::co::colensobbdo::dlib::proto::Landmark* mutable_landmarks(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Landmark >*
      mutable_landmarks();
  private:
  const ::nz::co::colensobbdo::dlib::proto::Landmark& _internal_landmarks(int index) const;
  ::nz::co::colensobbdo::dlib::proto::Landmark* _internal_add_landmarks();
  public:
  const ::nz::co::colensobbdo::dlib::proto::Landmark& landmarks(int index) const;
  ::nz::co::colensobbdo::dlib::proto::Landmark* add_landmarks();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Landmark >&
      landmarks() const;

  // @@protoc_insertion_point(class_scope:nz.co.colensobbdo.dlib.proto.LandmarkList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Landmark > landmarks_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class RectF final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nz.co.colensobbdo.dlib.proto.RectF) */ {
 public:
  inline RectF() : RectF(nullptr) {}
  ~RectF() override;
  explicit constexpr RectF(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RectF(const RectF& from);
  RectF(RectF&& from) noexcept
    : RectF() {
    *this = ::std::move(from);
  }

  inline RectF& operator=(const RectF& from) {
    CopyFrom(from);
    return *this;
  }
  inline RectF& operator=(RectF&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RectF& default_instance() {
    return *internal_default_instance();
  }
  static inline const RectF* internal_default_instance() {
    return reinterpret_cast<const RectF*>(
               &_RectF_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RectF& a, RectF& b) {
    a.Swap(&b);
  }
  inline void Swap(RectF* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RectF* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RectF* New() const final {
    return new RectF();
  }

  RectF* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RectF>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RectF& from);
  void MergeFrom(const RectF& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RectF* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nz.co.colensobbdo.dlib.proto.RectF";
  }
  protected:
  explicit RectF(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLeftFieldNumber = 1,
    kTopFieldNumber = 2,
    kRightFieldNumber = 3,
    kBottomFieldNumber = 4,
  };
  // float left = 1;
  void clear_left();
  float left() const;
  void set_left(float value);
  private:
  float _internal_left() const;
  void _internal_set_left(float value);
  public:

  // float top = 2;
  void clear_top();
  float top() const;
  void set_top(float value);
  private:
  float _internal_top() const;
  void _internal_set_top(float value);
  public:

  // float right = 3;
  void clear_right();
  float right() const;
  void set_right(float value);
  private:
  float _internal_right() const;
  void _internal_set_right(float value);
  public:

  // float bottom = 4;
  void clear_bottom();
  float bottom() const;
  void set_bottom(float value);
  private:
  float _internal_bottom() const;
  void _internal_set_bottom(float value);
  public:

  // @@protoc_insertion_point(class_scope:nz.co.colensobbdo.dlib.proto.RectF)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float left_;
  float top_;
  float right_;
  float bottom_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class RectFList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nz.co.colensobbdo.dlib.proto.RectFList) */ {
 public:
  inline RectFList() : RectFList(nullptr) {}
  ~RectFList() override;
  explicit constexpr RectFList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RectFList(const RectFList& from);
  RectFList(RectFList&& from) noexcept
    : RectFList() {
    *this = ::std::move(from);
  }

  inline RectFList& operator=(const RectFList& from) {
    CopyFrom(from);
    return *this;
  }
  inline RectFList& operator=(RectFList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RectFList& default_instance() {
    return *internal_default_instance();
  }
  static inline const RectFList* internal_default_instance() {
    return reinterpret_cast<const RectFList*>(
               &_RectFList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(RectFList& a, RectFList& b) {
    a.Swap(&b);
  }
  inline void Swap(RectFList* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RectFList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RectFList* New() const final {
    return new RectFList();
  }

  RectFList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RectFList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RectFList& from);
  void MergeFrom(const RectFList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RectFList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nz.co.colensobbdo.dlib.proto.RectFList";
  }
  protected:
  explicit RectFList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRectsFieldNumber = 1,
  };
  // repeated .nz.co.colensobbdo.dlib.proto.RectF rects = 1;
  int rects_size() const;
  private:
  int _internal_rects_size() const;
  public:
  void clear_rects();
  ::nz::co::colensobbdo::dlib::proto::RectF* mutable_rects(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::RectF >*
      mutable_rects();
  private:
  const ::nz::co::colensobbdo::dlib::proto::RectF& _internal_rects(int index) const;
  ::nz::co::colensobbdo::dlib::proto::RectF* _internal_add_rects();
  public:
  const ::nz::co::colensobbdo::dlib::proto::RectF& rects(int index) const;
  ::nz::co::colensobbdo::dlib::proto::RectF* add_rects();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::RectF >&
      rects() const;

  // @@protoc_insertion_point(class_scope:nz.co.colensobbdo.dlib.proto.RectFList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::RectF > rects_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class Face final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nz.co.colensobbdo.dlib.proto.Face) */ {
 public:
  inline Face() : Face(nullptr) {}
  ~Face() override;
  explicit constexpr Face(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Face(const Face& from);
  Face(Face&& from) noexcept
    : Face() {
    *this = ::std::move(from);
  }

  inline Face& operator=(const Face& from) {
    CopyFrom(from);
    return *this;
  }
  inline Face& operator=(Face&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Face& default_instance() {
    return *internal_default_instance();
  }
  static inline const Face* internal_default_instance() {
    return reinterpret_cast<const Face*>(
               &_Face_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Face& a, Face& b) {
    a.Swap(&b);
  }
  inline void Swap(Face* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Face* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Face* New() const final {
    return new Face();
  }

  Face* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Face>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Face& from);
  void MergeFrom(const Face& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Face* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nz.co.colensobbdo.dlib.proto.Face";
  }
  protected:
  explicit Face(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLandmarksFieldNumber = 2,
    kBoundFieldNumber = 1,
  };
  // repeated .nz.co.colensobbdo.dlib.proto.Landmark landmarks = 2;
  int landmarks_size() const;
  private:
  int _internal_landmarks_size() const;
  public:
  void clear_landmarks();
  ::nz::co::colensobbdo::dlib::proto::Landmark* mutable_landmarks(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Landmark >*
      mutable_landmarks();
  private:
  const ::nz::co::colensobbdo::dlib::proto::Landmark& _internal_landmarks(int index) const;
  ::nz::co::colensobbdo::dlib::proto::Landmark* _internal_add_landmarks();
  public:
  const ::nz::co::colensobbdo::dlib::proto::Landmark& landmarks(int index) const;
  ::nz::co::colensobbdo::dlib::proto::Landmark* add_landmarks();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Landmark >&
      landmarks() const;

  // .nz.co.colensobbdo.dlib.proto.RectF bound = 1;
  bool has_bound() const;
  private:
  bool _internal_has_bound() const;
  public:
  void clear_bound();
  const ::nz::co::colensobbdo::dlib::proto::RectF& bound() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::nz::co::colensobbdo::dlib::proto::RectF* release_bound();
  ::nz::co::colensobbdo::dlib::proto::RectF* mutable_bound();
  void set_allocated_bound(::nz::co::colensobbdo::dlib::proto::RectF* bound);
  private:
  const ::nz::co::colensobbdo::dlib::proto::RectF& _internal_bound() const;
  ::nz::co::colensobbdo::dlib::proto::RectF* _internal_mutable_bound();
  public:
  void unsafe_arena_set_allocated_bound(
      ::nz::co::colensobbdo::dlib::proto::RectF* bound);
  ::nz::co::colensobbdo::dlib::proto::RectF* unsafe_arena_release_bound();

  // @@protoc_insertion_point(class_scope:nz.co.colensobbdo.dlib.proto.Face)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Landmark > landmarks_;
  ::nz::co::colensobbdo::dlib::proto::RectF* bound_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class FaceList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nz.co.colensobbdo.dlib.proto.FaceList) */ {
 public:
  inline FaceList() : FaceList(nullptr) {}
  ~FaceList() override;
  explicit constexpr FaceList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FaceList(const FaceList& from);
  FaceList(FaceList&& from) noexcept
    : FaceList() {
    *this = ::std::move(from);
  }

  inline FaceList& operator=(const FaceList& from) {
    CopyFrom(from);
    return *this;
  }
  inline FaceList& operator=(FaceList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FaceList& default_instance() {
    return *internal_default_instance();
  }
  static inline const FaceList* internal_default_instance() {
    return reinterpret_cast<const FaceList*>(
               &_FaceList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(FaceList& a, FaceList& b) {
    a.Swap(&b);
  }
  inline void Swap(FaceList* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FaceList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FaceList* New() const final {
    return new FaceList();
  }

  FaceList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FaceList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FaceList& from);
  void MergeFrom(const FaceList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FaceList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nz.co.colensobbdo.dlib.proto.FaceList";
  }
  protected:
  explicit FaceList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFacesFieldNumber = 1,
  };
  // repeated .nz.co.colensobbdo.dlib.proto.Face faces = 1;
  int faces_size() const;
  private:
  int _internal_faces_size() const;
  public:
  void clear_faces();
  ::nz::co::colensobbdo::dlib::proto::Face* mutable_faces(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Face >*
      mutable_faces();
  private:
  const ::nz::co::colensobbdo::dlib::proto::Face& _internal_faces(int index) const;
  ::nz::co::colensobbdo::dlib::proto::Face* _internal_add_faces();
  public:
  const ::nz::co::colensobbdo::dlib::proto::Face& faces(int index) const;
  ::nz::co::colensobbdo::dlib::proto::Face* add_faces();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Face >&
      faces() const;

  // @@protoc_insertion_point(class_scope:nz.co.colensobbdo.dlib.proto.FaceList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Face > faces_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_messages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Landmark

// float x = 1;
inline void Landmark::clear_x() {
  x_ = 0;
}
inline float Landmark::_internal_x() const {
  return x_;
}
inline float Landmark::x() const {
  // @@protoc_insertion_point(field_get:nz.co.colensobbdo.dlib.proto.Landmark.x)
  return _internal_x();
}
inline void Landmark::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Landmark::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:nz.co.colensobbdo.dlib.proto.Landmark.x)
}

// float y = 2;
inline void Landmark::clear_y() {
  y_ = 0;
}
inline float Landmark::_internal_y() const {
  return y_;
}
inline float Landmark::y() const {
  // @@protoc_insertion_point(field_get:nz.co.colensobbdo.dlib.proto.Landmark.y)
  return _internal_y();
}
inline void Landmark::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Landmark::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:nz.co.colensobbdo.dlib.proto.Landmark.y)
}

// -------------------------------------------------------------------

// LandmarkList

// repeated .nz.co.colensobbdo.dlib.proto.Landmark landmarks = 1;
inline int LandmarkList::_internal_landmarks_size() const {
  return landmarks_.size();
}
inline int LandmarkList::landmarks_size() const {
  return _internal_landmarks_size();
}
inline void LandmarkList::clear_landmarks() {
  landmarks_.Clear();
}
inline ::nz::co::colensobbdo::dlib::proto::Landmark* LandmarkList::mutable_landmarks(int index) {
  // @@protoc_insertion_point(field_mutable:nz.co.colensobbdo.dlib.proto.LandmarkList.landmarks)
  return landmarks_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Landmark >*
LandmarkList::mutable_landmarks() {
  // @@protoc_insertion_point(field_mutable_list:nz.co.colensobbdo.dlib.proto.LandmarkList.landmarks)
  return &landmarks_;
}
inline const ::nz::co::colensobbdo::dlib::proto::Landmark& LandmarkList::_internal_landmarks(int index) const {
  return landmarks_.Get(index);
}
inline const ::nz::co::colensobbdo::dlib::proto::Landmark& LandmarkList::landmarks(int index) const {
  // @@protoc_insertion_point(field_get:nz.co.colensobbdo.dlib.proto.LandmarkList.landmarks)
  return _internal_landmarks(index);
}
inline ::nz::co::colensobbdo::dlib::proto::Landmark* LandmarkList::_internal_add_landmarks() {
  return landmarks_.Add();
}
inline ::nz::co::colensobbdo::dlib::proto::Landmark* LandmarkList::add_landmarks() {
  // @@protoc_insertion_point(field_add:nz.co.colensobbdo.dlib.proto.LandmarkList.landmarks)
  return _internal_add_landmarks();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Landmark >&
LandmarkList::landmarks() const {
  // @@protoc_insertion_point(field_list:nz.co.colensobbdo.dlib.proto.LandmarkList.landmarks)
  return landmarks_;
}

// -------------------------------------------------------------------

// RectF

// float left = 1;
inline void RectF::clear_left() {
  left_ = 0;
}
inline float RectF::_internal_left() const {
  return left_;
}
inline float RectF::left() const {
  // @@protoc_insertion_point(field_get:nz.co.colensobbdo.dlib.proto.RectF.left)
  return _internal_left();
}
inline void RectF::_internal_set_left(float value) {
  
  left_ = value;
}
inline void RectF::set_left(float value) {
  _internal_set_left(value);
  // @@protoc_insertion_point(field_set:nz.co.colensobbdo.dlib.proto.RectF.left)
}

// float top = 2;
inline void RectF::clear_top() {
  top_ = 0;
}
inline float RectF::_internal_top() const {
  return top_;
}
inline float RectF::top() const {
  // @@protoc_insertion_point(field_get:nz.co.colensobbdo.dlib.proto.RectF.top)
  return _internal_top();
}
inline void RectF::_internal_set_top(float value) {
  
  top_ = value;
}
inline void RectF::set_top(float value) {
  _internal_set_top(value);
  // @@protoc_insertion_point(field_set:nz.co.colensobbdo.dlib.proto.RectF.top)
}

// float right = 3;
inline void RectF::clear_right() {
  right_ = 0;
}
inline float RectF::_internal_right() const {
  return right_;
}
inline float RectF::right() const {
  // @@protoc_insertion_point(field_get:nz.co.colensobbdo.dlib.proto.RectF.right)
  return _internal_right();
}
inline void RectF::_internal_set_right(float value) {
  
  right_ = value;
}
inline void RectF::set_right(float value) {
  _internal_set_right(value);
  // @@protoc_insertion_point(field_set:nz.co.colensobbdo.dlib.proto.RectF.right)
}

// float bottom = 4;
inline void RectF::clear_bottom() {
  bottom_ = 0;
}
inline float RectF::_internal_bottom() const {
  return bottom_;
}
inline float RectF::bottom() const {
  // @@protoc_insertion_point(field_get:nz.co.colensobbdo.dlib.proto.RectF.bottom)
  return _internal_bottom();
}
inline void RectF::_internal_set_bottom(float value) {
  
  bottom_ = value;
}
inline void RectF::set_bottom(float value) {
  _internal_set_bottom(value);
  // @@protoc_insertion_point(field_set:nz.co.colensobbdo.dlib.proto.RectF.bottom)
}

// -------------------------------------------------------------------

// RectFList

// repeated .nz.co.colensobbdo.dlib.proto.RectF rects = 1;
inline int RectFList::_internal_rects_size() const {
  return rects_.size();
}
inline int RectFList::rects_size() const {
  return _internal_rects_size();
}
inline void RectFList::clear_rects() {
  rects_.Clear();
}
inline ::nz::co::colensobbdo::dlib::proto::RectF* RectFList::mutable_rects(int index) {
  // @@protoc_insertion_point(field_mutable:nz.co.colensobbdo.dlib.proto.RectFList.rects)
  return rects_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::RectF >*
RectFList::mutable_rects() {
  // @@protoc_insertion_point(field_mutable_list:nz.co.colensobbdo.dlib.proto.RectFList.rects)
  return &rects_;
}
inline const ::nz::co::colensobbdo::dlib::proto::RectF& RectFList::_internal_rects(int index) const {
  return rects_.Get(index);
}
inline const ::nz::co::colensobbdo::dlib::proto::RectF& RectFList::rects(int index) const {
  // @@protoc_insertion_point(field_get:nz.co.colensobbdo.dlib.proto.RectFList.rects)
  return _internal_rects(index);
}
inline ::nz::co::colensobbdo::dlib::proto::RectF* RectFList::_internal_add_rects() {
  return rects_.Add();
}
inline ::nz::co::colensobbdo::dlib::proto::RectF* RectFList::add_rects() {
  // @@protoc_insertion_point(field_add:nz.co.colensobbdo.dlib.proto.RectFList.rects)
  return _internal_add_rects();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::RectF >&
RectFList::rects() const {
  // @@protoc_insertion_point(field_list:nz.co.colensobbdo.dlib.proto.RectFList.rects)
  return rects_;
}

// -------------------------------------------------------------------

// Face

// .nz.co.colensobbdo.dlib.proto.RectF bound = 1;
inline bool Face::_internal_has_bound() const {
  return this != internal_default_instance() && bound_ != nullptr;
}
inline bool Face::has_bound() const {
  return _internal_has_bound();
}
inline void Face::clear_bound() {
  if (GetArenaForAllocation() == nullptr && bound_ != nullptr) {
    delete bound_;
  }
  bound_ = nullptr;
}
inline const ::nz::co::colensobbdo::dlib::proto::RectF& Face::_internal_bound() const {
  const ::nz::co::colensobbdo::dlib::proto::RectF* p = bound_;
  return p != nullptr ? *p : reinterpret_cast<const ::nz::co::colensobbdo::dlib::proto::RectF&>(
      ::nz::co::colensobbdo::dlib::proto::_RectF_default_instance_);
}
inline const ::nz::co::colensobbdo::dlib::proto::RectF& Face::bound() const {
  // @@protoc_insertion_point(field_get:nz.co.colensobbdo.dlib.proto.Face.bound)
  return _internal_bound();
}
inline void Face::unsafe_arena_set_allocated_bound(
    ::nz::co::colensobbdo::dlib::proto::RectF* bound) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(bound_);
  }
  bound_ = bound;
  if (bound) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nz.co.colensobbdo.dlib.proto.Face.bound)
}
inline ::nz::co::colensobbdo::dlib::proto::RectF* Face::release_bound() {
  
  ::nz::co::colensobbdo::dlib::proto::RectF* temp = bound_;
  bound_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::nz::co::colensobbdo::dlib::proto::RectF* Face::unsafe_arena_release_bound() {
  // @@protoc_insertion_point(field_release:nz.co.colensobbdo.dlib.proto.Face.bound)
  
  ::nz::co::colensobbdo::dlib::proto::RectF* temp = bound_;
  bound_ = nullptr;
  return temp;
}
inline ::nz::co::colensobbdo::dlib::proto::RectF* Face::_internal_mutable_bound() {
  
  if (bound_ == nullptr) {
    auto* p = CreateMaybeMessage<::nz::co::colensobbdo::dlib::proto::RectF>(GetArenaForAllocation());
    bound_ = p;
  }
  return bound_;
}
inline ::nz::co::colensobbdo::dlib::proto::RectF* Face::mutable_bound() {
  // @@protoc_insertion_point(field_mutable:nz.co.colensobbdo.dlib.proto.Face.bound)
  return _internal_mutable_bound();
}
inline void Face::set_allocated_bound(::nz::co::colensobbdo::dlib::proto::RectF* bound) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete bound_;
  }
  if (bound) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::nz::co::colensobbdo::dlib::proto::RectF>::GetOwningArena(bound);
    if (message_arena != submessage_arena) {
      bound = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, bound, submessage_arena);
    }
    
  } else {
    
  }
  bound_ = bound;
  // @@protoc_insertion_point(field_set_allocated:nz.co.colensobbdo.dlib.proto.Face.bound)
}

// repeated .nz.co.colensobbdo.dlib.proto.Landmark landmarks = 2;
inline int Face::_internal_landmarks_size() const {
  return landmarks_.size();
}
inline int Face::landmarks_size() const {
  return _internal_landmarks_size();
}
inline void Face::clear_landmarks() {
  landmarks_.Clear();
}
inline ::nz::co::colensobbdo::dlib::proto::Landmark* Face::mutable_landmarks(int index) {
  // @@protoc_insertion_point(field_mutable:nz.co.colensobbdo.dlib.proto.Face.landmarks)
  return landmarks_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Landmark >*
Face::mutable_landmarks() {
  // @@protoc_insertion_point(field_mutable_list:nz.co.colensobbdo.dlib.proto.Face.landmarks)
  return &landmarks_;
}
inline const ::nz::co::colensobbdo::dlib::proto::Landmark& Face::_internal_landmarks(int index) const {
  return landmarks_.Get(index);
}
inline const ::nz::co::colensobbdo::dlib::proto::Landmark& Face::landmarks(int index) const {
  // @@protoc_insertion_point(field_get:nz.co.colensobbdo.dlib.proto.Face.landmarks)
  return _internal_landmarks(index);
}
inline ::nz::co::colensobbdo::dlib::proto::Landmark* Face::_internal_add_landmarks() {
  return landmarks_.Add();
}
inline ::nz::co::colensobbdo::dlib::proto::Landmark* Face::add_landmarks() {
  // @@protoc_insertion_point(field_add:nz.co.colensobbdo.dlib.proto.Face.landmarks)
  return _internal_add_landmarks();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Landmark >&
Face::landmarks() const {
  // @@protoc_insertion_point(field_list:nz.co.colensobbdo.dlib.proto.Face.landmarks)
  return landmarks_;
}

// -------------------------------------------------------------------

// FaceList

// repeated .nz.co.colensobbdo.dlib.proto.Face faces = 1;
inline int FaceList::_internal_faces_size() const {
  return faces_.size();
}
inline int FaceList::faces_size() const {
  return _internal_faces_size();
}
inline void FaceList::clear_faces() {
  faces_.Clear();
}
inline ::nz::co::colensobbdo::dlib::proto::Face* FaceList::mutable_faces(int index) {
  // @@protoc_insertion_point(field_mutable:nz.co.colensobbdo.dlib.proto.FaceList.faces)
  return faces_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Face >*
FaceList::mutable_faces() {
  // @@protoc_insertion_point(field_mutable_list:nz.co.colensobbdo.dlib.proto.FaceList.faces)
  return &faces_;
}
inline const ::nz::co::colensobbdo::dlib::proto::Face& FaceList::_internal_faces(int index) const {
  return faces_.Get(index);
}
inline const ::nz::co::colensobbdo::dlib::proto::Face& FaceList::faces(int index) const {
  // @@protoc_insertion_point(field_get:nz.co.colensobbdo.dlib.proto.FaceList.faces)
  return _internal_faces(index);
}
inline ::nz::co::colensobbdo::dlib::proto::Face* FaceList::_internal_add_faces() {
  return faces_.Add();
}
inline ::nz::co::colensobbdo::dlib::proto::Face* FaceList::add_faces() {
  // @@protoc_insertion_point(field_add:nz.co.colensobbdo.dlib.proto.FaceList.faces)
  return _internal_add_faces();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nz::co::colensobbdo::dlib::proto::Face >&
FaceList::faces() const {
  // @@protoc_insertion_point(field_list:nz.co.colensobbdo.dlib.proto.FaceList.faces)
  return faces_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace dlib
}  // namespace colensobbdo
}  // namespace co
}  // namespace nz

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_messages_2eproto
